# Generated by Django 2.2.6 on 2019-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_confirmed',
            field=models.DateTimeField(null=True, verbose_name='date confirmed'),
        ),
    ]
